version: "3.8"

services:

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: always

  influxdb:
    container_name: influxdb
    image: influxdb
    volumes:
      - influxdb:/var/lib/influxdb 
    restart: always

  telegraf:
    container_name: telegraf
    image: telegraf
    volumes:
      - telegraf:/etc/telegraf:ro
    restart: always

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongo:/data/db
    restart: always

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "8081:8081"
    restart: always
      
  nodered:
    container_name: nodered
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - nodered:/data 
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    restart: always

volumes:
  mosquitto:
  influxdb:
  telegraf:
  mongo:
  nodered:
  grafana:
