version: "3.8"

volumes:
  influxdb:
  telegraf:
  mongo:
  nodered:

services:
  mosquitto:
    image: eclipse-mosquitto
    restart: always

  influxdb:
    image: influxdb
    volumes:
      - influxdb:/var/lib/influxdb 
    restart: always

  telegraf:
    image: telegraf
    volumes:
      - telegraf:/etc/telegraf:ro
    restart: always

  mongo:
    image: mongo
    volumes:
      - mongo:/data/db
    restart: always

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    restart: always
      
  nodered:
    image: nodered/node-red
    ports:
      - 1880:1880
    volumes:
      - nodered:/data 
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    restart: always
